#!/bin/sh
# Fix Notes exported from Zotero

# 24 is the line where annotations should usually start
# - replace unicode quotes by normal quotes
# - newlines after quotes
# - spilt my notes into new lines
sed -i -e "1,$ {s/<[^>]*>//g;s/\[\[0[0-9] /[[/g;s/[“”]/\"/g;s/^\"/\n>\"/g;s/p. [0-9]\+)/\0\n\n/g}" "$OBS/_Inbox/$(lastTouched "$OBS/_Inbox")" 
sed -i '/^$/N;/^\n$/D' "$OBS/_Inbox/$(lastTouched "$OBS/_Inbox")" 
