#!/usr/bin/env bash
# Categorize Inbox files with fzf

set -o errexit
set -o nounset
set -o pipefail
if [[ -n "${TRACE-}" ]]; then
    set -o xtrace
fi

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
    echo 'Usage: ./script.sh arg-one arg-two

This is an awesome bash script to make your life better.

'
    exit
fi

cd "$OBS"

main() {
    for fname in _Inbox/*.md; do
        movedir=$(find . -type d -not -path "_Inbox" | fzf --preview "cat \"$fname\"" --preview-label="$fname" -i) 
        if [[ "$movedir" == "./_Inbox" || "$movedir" == "." || "$movedir" == "_Inbox" ]]; then
            echo "Keeping $fname in _Inbox"
        else
            mv "$fname" "$movedir"
        fi
    done
}

main "$@"
