#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ -n "${TRACE-}" ]]; then
    set -o xtrace
fi

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
    echo 'Usage: ./script.sh arg-one arg-two

This is an awesome bash script to make your life better.

'
    exit
fi

cd "$(dirname "$0")"

main() {
    file=`ls -1t $DOWNLOADS | head -1`
    mv --verbose "$DOWNLOADS/$file" "$HOME/workspace/archive/40 Telic Activities/46 Tools/46.04 paperless/paperless-ngx/consume"
}

main "$@"
