#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ -n "${TRACE-}" ]]; then
    set -o xtrace
fi

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
    echo 'Usage: ./script.sh arg-one arg-two

This is an awesome bash script to make your life better.

'
    exit
fi

cd "$(dirname "$0")"

main() {
    timestamp=$(date +"%Y-%m-%d_%H%M")
    
    for file in "$ICLOUD/paperless consume/"*.pdf; do
        [ -e "$file" ] || continue
        filename=$(basename "$file" .pdf)
        newname="${timestamp}_${filename}.pdf"
        scp "$file" "192.168.178.26:/home/stefan/paperless-ngx/consume/${newname}"
        mv "$file" "$ICLOUD/paperless consume/processed/${newname}"
    done
}

main "$@"
